### ISSUE TITLE
프론트 환경설정

### ISSUE THREAD

**Issue by chaeryeon823** [boostcampwm-2024/web18-inear#1]
### 📌 Summary
스토리북 활용을 위한 설정과정 입니다
### ✔️ Todo
- [ ] 스토리북 설치
- [x] 간단한 버튼 컴포넌트로 테스트
- [x] tailwind 설정
- [x] 절대 경로 설정
- [x] 커스텀 색상 정리
